[contract]
    # file names without .sol extention
    contracts  = [
        # "Test", "FPS"
        "FPS"
    ]

    #[contract.Test]
        # contract name
      #  name = "Test"
        # eventName = "MessageChanged"
        # constuctor parameters
#        paremeters = [1, 2, 3]

    [contract.FPS]
        # contract name
        name = "FPS"
        # eventName = "StorageRequest"
        # constuctor parameters
#        paremeters = [1, 2, 3]

